# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_item_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogItemEdit(object):
    def setupUi(self, catalogItemEdit):
        catalogItemEdit.setObjectName("catalogItemEdit")
        catalogItemEdit.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(catalogItemEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(catalogItemEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 1)

        self.retranslateUi(catalogItemEdit)
        self.buttonBox.accepted.connect(catalogItemEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(catalogItemEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(catalogItemEdit)

    def retranslateUi(self, catalogItemEdit):
        _translate = QtCore.QCoreApplication.translate
        catalogItemEdit.setWindowTitle(_translate("catalogItemEdit", "Item Edit"))
