# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\templateBtns.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_templateBtns(object):
    def setupUi(self, templateBtns):
        templateBtns.setObjectName("templateBtns")
        templateBtns.resize(120, 24)
        self.gridLayout = QtWidgets.QGridLayout(templateBtns)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.createProfile = QtWidgets.QPushButton(templateBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createProfile.sizePolicy().hasHeightForWidth())
        self.createProfile.setSizePolicy(sizePolicy)
        self.createProfile.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/drawable-hdpi-v4/addbtn_menu21a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createProfile.setIcon(icon)
        self.createProfile.setObjectName("createProfile")
        self.gridLayout.addWidget(self.createProfile, 0, 0, 1, 1)
        self.delBtn = QtWidgets.QPushButton(templateBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delBtn.sizePolicy().hasHeightForWidth())
        self.delBtn.setSizePolicy(sizePolicy)
        self.delBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons19/res/drawable-xhdpi-v4/deletebtn21a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delBtn.setIcon(icon1)
        self.delBtn.setObjectName("delBtn")
        self.gridLayout.addWidget(self.delBtn, 0, 1, 1, 1)

        self.retranslateUi(templateBtns)
        QtCore.QMetaObject.connectSlotsByName(templateBtns)

    def retranslateUi(self, templateBtns):
        _translate = QtCore.QCoreApplication.translate
        templateBtns.setWindowTitle(_translate("templateBtns", "Form"))
import res_rc
