# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\bc_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bcEdit(object):
    def setupUi(self, bcEdit):
        bcEdit.setObjectName("bcEdit")
        bcEdit.resize(174, 93)
        self.gridLayout = QtWidgets.QGridLayout(bcEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(bcEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(bcEdit)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 0, 0, 1, 1)

        self.retranslateUi(bcEdit)
        self.buttonBox.accepted.connect(bcEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(bcEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(bcEdit)

    def retranslateUi(self, bcEdit):
        _translate = QtCore.QCoreApplication.translate
        bcEdit.setWindowTitle(_translate("bcEdit", "BC Edit"))
