# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\add_btn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tWidget(object):
    def setupUi(self, tWidget):
        tWidget.setObjectName("tWidget")
        tWidget.resize(380, 20)
        tWidget.setMaximumSize(QtCore.QSize(386, 16777215))
        tWidget.setStyleSheet("QWidget#zWidget, QWidget#tWidget {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgb(51, 51, 51);\n"
"    color: rgb(95, 95, 95);\n"
"    font-size: 15px;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: rgb(76, 76, 76);\n"
"}\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(tWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.add = QtWidgets.QPushButton(tWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setMinimumSize(QtCore.QSize(0, 0))
        self.add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/drawable-hdpi-v4/addbtn_menu21b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(20, 20))
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 0, 1, 1)

        self.retranslateUi(tWidget)
        QtCore.QMetaObject.connectSlotsByName(tWidget)

    def retranslateUi(self, tWidget):
        _translate = QtCore.QCoreApplication.translate
        tWidget.setWindowTitle(_translate("tWidget", "Form"))
        self.add.setText(_translate("tWidget", "Add Profile"))
import res_rc
