# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\add_btn.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tWidget(object):
    def setupUi(self, tWidget):
        tWidget.setObjectName("tWidget")
        tWidget.resize(382, 20)
        tWidget.setStyleSheet("QWidget#zWidget, QWidget#tWidget {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: transparent;\n"
"    border: 0px;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(tWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.add = QtWidgets.QPushButton(tWidget)
        self.add.setMinimumSize(QtCore.QSize(70, 0))
        self.add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/drawable-hdpi-v4/addbtn_menu21b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(20, 20))
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)

        self.retranslateUi(tWidget)
        QtCore.QMetaObject.connectSlotsByName(tWidget)

    def retranslateUi(self, tWidget):
        _translate = QtCore.QCoreApplication.translate
        tWidget.setWindowTitle(_translate("tWidget", "Form"))
import res_rc
