# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\profiles_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profilesTable(object):
    def setupUi(self, profilesTable):
        profilesTable.setObjectName("profilesTable")
        profilesTable.resize(426, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profilesTable.sizePolicy().hasHeightForWidth())
        profilesTable.setSizePolicy(sizePolicy)
        profilesTable.setMinimumSize(QtCore.QSize(426, 1))
        profilesTable.setMaximumSize(QtCore.QSize(426, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(profilesTable)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(profilesTable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(426, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(426, 16777215))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    \n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(415)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(415)
        self.tableWidget.verticalHeader().setDefaultSectionSize(60)
        self.tableWidget.verticalHeader().setMinimumSectionSize(60)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(profilesTable)
        QtCore.QMetaObject.connectSlotsByName(profilesTable)

    def retranslateUi(self, profilesTable):
        _translate = QtCore.QCoreApplication.translate
        profilesTable.setWindowTitle(_translate("profilesTable", "Form"))
