# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\profiles_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profilesProgress(object):
    def setupUi(self, profilesProgress):
        profilesProgress.setObjectName("profilesProgress")
        profilesProgress.resize(126, 26)
        self.gridLayout = QtWidgets.QGridLayout(profilesProgress)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(profilesProgress)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 8))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(50, 63, 57);\n"
"    \n"
"} \n"
"\n"
"QProgressBar::text::highlighted {\n"
"    color: white;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)

        self.retranslateUi(profilesProgress)
        QtCore.QMetaObject.connectSlotsByName(profilesProgress)

    def retranslateUi(self, profilesProgress):
        _translate = QtCore.QCoreApplication.translate
        profilesProgress.setWindowTitle(_translate("profilesProgress", "Form"))
        self.progressBar.setFormat(_translate("profilesProgress", "%p%"))
