# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\profile_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_profileItem(object):
    def setupUi(self, profileItem):
        profileItem.setObjectName("profileItem")
        profileItem.resize(380, 60)
        profileItem.setMinimumSize(QtCore.QSize(380, 60))
        profileItem.setMaximumSize(QtCore.QSize(380, 60))
        profileItem.setStyleSheet("QWidget {\n"
"    background-color: rgb(55, 52, 63);\n"
"    border: 1px solid rgb(78, 78, 78);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button { width: 20px; }\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button { width: 20px; }\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: rgb(40, 40, 40);\n"
"    alternate-background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0;\n"
"}\n"
"QLineEdit, QLabel, QComboBox, QPushButton, QToolButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 0px solid grey;\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(profileItem)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(profileItem)
        self.widget_2.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("QWidget {background-color: black;\n"
"color: black;\n"
"font-size: 16px;\n"
"font-family: \"Bahnschrift Light Condensed\";}\n"
"QLabel {\n"
"    background-color: white;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.caliberShort = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caliberShort.sizePolicy().hasHeightForWidth())
        self.caliberShort.setSizePolicy(sizePolicy)
        self.caliberShort.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.caliberShort.setFont(font)
        self.caliberShort.setStyleSheet("")
        self.caliberShort.setAlignment(QtCore.Qt.AlignCenter)
        self.caliberShort.setObjectName("caliberShort")
        self.verticalLayout_2.addWidget(self.caliberShort)
        self.weightTile = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightTile.sizePolicy().hasHeightForWidth())
        self.weightTile.setSizePolicy(sizePolicy)
        self.weightTile.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.weightTile.setFont(font)
        self.weightTile.setStyleSheet("")
        self.weightTile.setAlignment(QtCore.Qt.AlignCenter)
        self.weightTile.setObjectName("weightTile")
        self.verticalLayout_2.addWidget(self.weightTile)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 2, 1)
        self.rifleName = QtWidgets.QLabel(profileItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rifleName.sizePolicy().hasHeightForWidth())
        self.rifleName.setSizePolicy(sizePolicy)
        self.rifleName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rifleName.setFont(font)
        self.rifleName.setObjectName("rifleName")
        self.gridLayout.addWidget(self.rifleName, 0, 1, 1, 1)
        self.cartridgeName = QtWidgets.QLabel(profileItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartridgeName.sizePolicy().hasHeightForWidth())
        self.cartridgeName.setSizePolicy(sizePolicy)
        self.cartridgeName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cartridgeName.setFont(font)
        self.cartridgeName.setObjectName("cartridgeName")
        self.gridLayout.addWidget(self.cartridgeName, 1, 1, 1, 1)

        self.retranslateUi(profileItem)
        QtCore.QMetaObject.connectSlotsByName(profileItem)

    def retranslateUi(self, profileItem):
        _translate = QtCore.QCoreApplication.translate
        profileItem.setWindowTitle(_translate("profileItem", "Form"))
        self.caliberShort.setText(_translate("profileItem", ".223Rem"))
        self.weightTile.setText(_translate("profileItem", "69"))
        self.rifleName.setText(_translate("profileItem", "223Rem 8TWIST"))
        self.cartridgeName.setText(_translate("profileItem", "ABR 69GR SMK"))
