from .drag_func_editor import DragFuncEditDialog
from .footer import FooterWidget
from .templates import Ui_MainWindow
from .templates import Ui_ArcheBCUpdate
from .lpc_install_dialog import LPC_dialog
from .recent_dialog import RecentDialog
from .profiles_tab import EmptyProfilesTab
from .single_custom_widgets import no_wheel_sb
from .catalog_tab import CatalogTab
