from .catalog_tab import Ui_catalogTab
from .catalog_selector import Ui_catalogSelector
from .catalog_info import Ui_catalogInfo
from .catalog_rifle import Ui_catalogRifle
from .catalog_bullet import Ui_catalogBullet
from .catalog_cartridge import Ui_catalogCartridge
from .catalog_item_edit import Ui_catalogItemEdit
from .catalog_rifle_list import Ui_catalogRifleList
from .catalog_cartridge_list import Ui_catalogCartridgeList
from .catalog_bullet_list import Ui_catalogBulletList
from .catalog_rifle_info import Ui_catalogRifleInfo
from .catalog_cartridge_info import Ui_catalogCartridgeInfo
from .catalog_bullet_info import Ui_catalogBulletInfo
from .selectorBtns import Ui_selectorBtns
