# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_rifle_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogRifleList(object):
    def setupUi(self, catalogRifleList):
        catalogRifleList.setObjectName("catalogRifleList")
        catalogRifleList.resize(535, 229)
        self.gridLayout = QtWidgets.QGridLayout(catalogRifleList)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(catalogRifleList)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(catalogRifleList)
        QtCore.QMetaObject.connectSlotsByName(catalogRifleList)

    def retranslateUi(self, catalogRifleList):
        _translate = QtCore.QCoreApplication.translate
        catalogRifleList.setWindowTitle(_translate("catalogRifleList", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("catalogRifleList", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("catalogRifleList", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("catalogRifleList", "Caliber"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("catalogRifleList", "Sight height"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("catalogRifleList", "Twist"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("catalogRifleList", "Copy"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("catalogRifleList", "Edit"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("catalogRifleList", "Delete"))
