# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_cartridge_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogCartridgeList(object):
    def setupUi(self, catalogCartridgeList):
        catalogCartridgeList.setObjectName("catalogCartridgeList")
        catalogCartridgeList.resize(535, 229)
        self.gridLayout = QtWidgets.QGridLayout(catalogCartridgeList)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(catalogCartridgeList)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(20)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(catalogCartridgeList)
        QtCore.QMetaObject.connectSlotsByName(catalogCartridgeList)

    def retranslateUi(self, catalogCartridgeList):
        _translate = QtCore.QCoreApplication.translate
        catalogCartridgeList.setWindowTitle(_translate("catalogCartridgeList", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("catalogCartridgeList", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("catalogCartridgeList", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("catalogCartridgeList", "Caliber"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("catalogCartridgeList", "Velocity"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("catalogCartridgeList", "Temp."))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("catalogCartridgeList", "Edit"))
