# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogInfo(object):
    def setupUi(self, catalogInfo):
        catalogInfo.setObjectName("catalogInfo")
        catalogInfo.resize(412, 300)
        catalogInfo.setMinimumSize(QtCore.QSize(412, 300))
        catalogInfo.setMaximumSize(QtCore.QSize(600, 16777215))

        self.retranslateUi(catalogInfo)
        QtCore.QMetaObject.connectSlotsByName(catalogInfo)

    def retranslateUi(self, catalogInfo):
        _translate = QtCore.QCoreApplication.translate
        catalogInfo.setWindowTitle(_translate("catalogInfo", "Form"))
