# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogTab(object):
    def setupUi(self, catalogTab):
        catalogTab.setObjectName("catalogTab")
        catalogTab.resize(463, 604)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(catalogTab.sizePolicy().hasHeightForWidth())
        catalogTab.setSizePolicy(sizePolicy)
        catalogTab.setMinimumSize(QtCore.QSize(0, 0))
        catalogTab.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(catalogTab)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(catalogTab)
        QtCore.QMetaObject.connectSlotsByName(catalogTab)

    def retranslateUi(self, catalogTab):
        _translate = QtCore.QCoreApplication.translate
        catalogTab.setWindowTitle(_translate("catalogTab", "Form"))
