# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\catalog_info_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogInfoTools(object):
    def setupUi(self, catalogInfoTools):
        catalogInfoTools.setObjectName("catalogInfoTools")
        catalogInfoTools.resize(504, 57)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(catalogInfoTools.sizePolicy().hasHeightForWidth())
        catalogInfoTools.setSizePolicy(sizePolicy)
        catalogInfoTools.setMaximumSize(QtCore.QSize(16777215, 60))
        self.gridLayout = QtWidgets.QGridLayout(catalogInfoTools)
        self.gridLayout.setObjectName("gridLayout")
        self.addTemplate = QtWidgets.QPushButton(catalogInfoTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTemplate.sizePolicy().hasHeightForWidth())
        self.addTemplate.setSizePolicy(sizePolicy)
        self.addTemplate.setObjectName("addTemplate")
        self.gridLayout.addWidget(self.addTemplate, 0, 0, 1, 1)

        self.retranslateUi(catalogInfoTools)
        QtCore.QMetaObject.connectSlotsByName(catalogInfoTools)

    def retranslateUi(self, catalogInfoTools):
        _translate = QtCore.QCoreApplication.translate
        catalogInfoTools.setWindowTitle(_translate("catalogInfoTools", "Form"))
        self.addTemplate.setText(_translate("catalogInfoTools", "Create template"))
