# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\mbc_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mbcEdit(object):
    def setupUi(self, mbcEdit):
        mbcEdit.setObjectName("mbcEdit")
        mbcEdit.resize(174, 237)
        self.gridLayout = QtWidgets.QGridLayout(mbcEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(mbcEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 1)

        self.retranslateUi(mbcEdit)
        self.buttonBox.accepted.connect(mbcEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(mbcEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mbcEdit)

    def retranslateUi(self, mbcEdit):
        _translate = QtCore.QCoreApplication.translate
        mbcEdit.setWindowTitle(_translate("mbcEdit", "BC Edit"))
