# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\selectorBtns.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectorBtns(object):
    def setupUi(self, selectorBtns):
        selectorBtns.setObjectName("selectorBtns")
        selectorBtns.resize(120, 24)
        self.gridLayout = QtWidgets.QGridLayout(selectorBtns)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.editBtn = QtWidgets.QPushButton(selectorBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editBtn.sizePolicy().hasHeightForWidth())
        self.editBtn.setSizePolicy(sizePolicy)
        self.editBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/custom/res/custom/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editBtn.setIcon(icon)
        self.editBtn.setObjectName("editBtn")
        self.gridLayout.addWidget(self.editBtn, 0, 1, 1, 1)
        self.delBtn = QtWidgets.QPushButton(selectorBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delBtn.sizePolicy().hasHeightForWidth())
        self.delBtn.setSizePolicy(sizePolicy)
        self.delBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons19/res/drawable-xhdpi-v4/deletebtn21a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delBtn.setIcon(icon1)
        self.delBtn.setObjectName("delBtn")
        self.gridLayout.addWidget(self.delBtn, 0, 2, 1, 1)
        self.copyBtn = QtWidgets.QPushButton(selectorBtns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyBtn.sizePolicy().hasHeightForWidth())
        self.copyBtn.setSizePolicy(sizePolicy)
        self.copyBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/drawable-v19/copynotification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copyBtn.setIcon(icon2)
        self.copyBtn.setObjectName("copyBtn")
        self.gridLayout.addWidget(self.copyBtn, 0, 0, 1, 1)

        self.retranslateUi(selectorBtns)
        QtCore.QMetaObject.connectSlotsByName(selectorBtns)

    def retranslateUi(self, selectorBtns):
        _translate = QtCore.QCoreApplication.translate
        selectorBtns.setWindowTitle(_translate("selectorBtns", "Form"))
import res_rc
