# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\archerbc_updater.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArcheBCUpdate(object):
    def setupUi(self, ArcheBCUpdate):
        ArcheBCUpdate.setObjectName("ArcheBCUpdate")
        ArcheBCUpdate.resize(516, 104)
        ArcheBCUpdate.setMinimumSize(QtCore.QSize(516, 104))
        ArcheBCUpdate.setMaximumSize(QtCore.QSize(516, 104))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_templates\\../.rsrc/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ArcheBCUpdate.setWindowIcon(icon)
        ArcheBCUpdate.setStyleSheet("QWidget {\n"
"    background-color: rgb(51, 51, 51);\n"
"    color: white;\n"
"}\n"
"QTabBar::tab {\n"
"    height: 40px; width: 100px;\n"
"    background-color: rgb(76, 76, 76);\n"
"    color: rgb(255, 170, 0);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 0px solid rgb(76, 76, 76);\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    border: 1px solid rgb(76, 76, 76);\n"
"    background-color:rgb(28, 28, 28); \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border: 0px solid rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTabBar::tab:!hover {\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTabWidget::pane { \n"
"    border: 2px solid rgb(76, 76, 76); \n"
"}\n"
"QScrollArea {\n"
"    border: 0; \n"
"}\n"
"\n"
"QProgressBar {\n"
"    background: white;\n"
"    color: black;\n"
"    margin-left: 8px;\n"
"    margin-right: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgb(50, 63, 57);\n"
"} \n"
"\n"
"QProgressBar::text::highlighted {\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(ArcheBCUpdate)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 6))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        ArcheBCUpdate.setCentralWidget(self.centralwidget)

        self.retranslateUi(ArcheBCUpdate)
        QtCore.QMetaObject.connectSlotsByName(ArcheBCUpdate)

    def retranslateUi(self, ArcheBCUpdate):
        _translate = QtCore.QCoreApplication.translate
        ArcheBCUpdate.setWindowTitle(_translate("ArcheBCUpdate", "ArcherBC Update"))
        self.label.setText(_translate("ArcheBCUpdate", "Looking for updates..."))
