# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\templates\drug_func_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 493)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(572, 493))
        Form.setMaximumSize(QtCore.QSize(572, 493))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui\\templates\\../../.rsrc/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(51, 51, 51);\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button { width: 20px; }\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button { width: 20px; }\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: rgb(40, 40, 40);\n"
"    alternate-background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit, QLabel, QComboBox, QPushButton, QToolButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 0px solid grey;\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"QGroupBox {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(78, 78, 78);\n"
"    padding-top: 25px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    padding: 5px 20px 5px 20px;\n"
"    color: rgb(255, 170, 0);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.Step = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step.sizePolicy().hasHeightForWidth())
        self.Step.setSizePolicy(sizePolicy)
        self.Step.setMaximum(100)
        self.Step.setObjectName("Step")
        self.gridLayout.addWidget(self.Step, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.PeakDown = QtWidgets.QPushButton(Form)
        self.PeakDown.setMinimumSize(QtCore.QSize(150, 0))
        self.PeakDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PeakDown.setObjectName("PeakDown")
        self.gridLayout.addWidget(self.PeakDown, 2, 2, 1, 1)
        self.PeakUp = QtWidgets.QPushButton(Form)
        self.PeakUp.setMinimumSize(QtCore.QSize(150, 0))
        self.PeakUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PeakUp.setObjectName("PeakUp")
        self.gridLayout.addWidget(self.PeakUp, 1, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(28)
        self.tableWidget.verticalHeader().setDefaultSectionSize(28)
        self.tableWidget.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 4)
        self.EndUp = QtWidgets.QPushButton(Form)
        self.EndUp.setMinimumSize(QtCore.QSize(150, 0))
        self.EndUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EndUp.setObjectName("EndUp")
        self.gridLayout.addWidget(self.EndUp, 1, 3, 1, 1)
        self.Down = QtWidgets.QPushButton(Form)
        self.Down.setMinimumSize(QtCore.QSize(150, 0))
        self.Down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Down.setObjectName("Down")
        self.gridLayout.addWidget(self.Down, 2, 1, 1, 1)
        self.Up = QtWidgets.QPushButton(Form)
        self.Up.setMinimumSize(QtCore.QSize(150, 0))
        self.Up.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Up.setObjectName("Up")
        self.gridLayout.addWidget(self.Up, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 4)
        self.EndDown = QtWidgets.QPushButton(Form)
        self.EndDown.setMinimumSize(QtCore.QSize(150, 0))
        self.EndDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EndDown.setObjectName("EndDown")
        self.gridLayout.addWidget(self.EndDown, 2, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Step.setSuffix(_translate("Form", " %"))
        self.label.setText(_translate("Form", "Step"))
        self.PeakDown.setText(_translate("Form", "Peak Down"))
        self.PeakUp.setText(_translate("Form", "Peak Up"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "v"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "i"))
        self.EndUp.setText(_translate("Form", "End Up"))
        self.Down.setText(_translate("Form", "Down"))
        self.Up.setText(_translate("Form", "Up"))
        self.EndDown.setText(_translate("Form", "End Down"))
