# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\footer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FooterWidget(object):
    def setupUi(self, FooterWidget):
        FooterWidget.setObjectName("FooterWidget")
        FooterWidget.resize(1006, 26)
        FooterWidget.setMinimumSize(QtCore.QSize(1006, 26))
        FooterWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        FooterWidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(FooterWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.autoConnect = QtWidgets.QCheckBox(FooterWidget)
        self.autoConnect.setStyleSheet("")
        self.autoConnect.setChecked(False)
        self.autoConnect.setObjectName("autoConnect")
        self.gridLayout.addWidget(self.autoConnect, 0, 0, 1, 1)
        self.connectionStatus = QtWidgets.QLabel(FooterWidget)
        self.connectionStatus.setObjectName("connectionStatus")
        self.gridLayout.addWidget(self.connectionStatus, 0, 1, 1, 1)
        self.Preferences = QtWidgets.QPushButton(FooterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preferences.sizePolicy().hasHeightForWidth())
        self.Preferences.setSizePolicy(sizePolicy)
        self.Preferences.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/custom/res/custom/tools.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Preferences.setIcon(icon)
        self.Preferences.setObjectName("Preferences")
        self.gridLayout.addWidget(self.Preferences, 0, 4, 1, 1)
        self.Language = QtWidgets.QComboBox(FooterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Language.sizePolicy().hasHeightForWidth())
        self.Language.setSizePolicy(sizePolicy)
        self.Language.setMinimumSize(QtCore.QSize(100, 0))
        self.Language.setObjectName("Language")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/flags/res/flags/united-kingdom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Language.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/flags/res/flags/ukraine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Language.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/flags/res/flags/russia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Language.addItem(icon3, "")
        self.gridLayout.addWidget(self.Language, 0, 3, 1, 1)

        self.retranslateUi(FooterWidget)
        QtCore.QMetaObject.connectSlotsByName(FooterWidget)

    def retranslateUi(self, FooterWidget):
        _translate = QtCore.QCoreApplication.translate
        FooterWidget.setWindowTitle(_translate("FooterWidget", "Form"))
        self.autoConnect.setText(_translate("FooterWidget", "Auto search"))
        self.connectionStatus.setText(_translate("FooterWidget", "No DFU device found"))
        self.Preferences.setToolTip(_translate("FooterWidget", "Preferences"))
        self.Preferences.setText(_translate("FooterWidget", "Settings"))
        self.Language.setItemText(0, _translate("FooterWidget", "English"))
        self.Language.setItemText(1, _translate("FooterWidget", "Українська"))
        self.Language.setItemText(2, _translate("FooterWidget", "Русский"))
import res_rc
