# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'footer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FooterWidget(object):
    def setupUi(self, footerWidget):
        footerWidget.setObjectName("footerWidget")
        footerWidget.resize(1006, 26)
        footerWidget.setMinimumSize(QtCore.QSize(1006, 26))
        footerWidget.setMaximumSize(QtCore.QSize(16777215, 26))
        self.horizontalLayout = QtWidgets.QHBoxLayout(footerWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectDevice = QtWidgets.QPushButton(footerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectDevice.sizePolicy().hasHeightForWidth())
        self.connectDevice.setSizePolicy(sizePolicy)
        self.connectDevice.setMinimumSize(QtCore.QSize(26, 26))
        self.connectDevice.setMaximumSize(QtCore.QSize(26, 26))
        self.connectDevice.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("old/.rsrc/res/drawable/arrowdownbtn21a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectDevice.setIcon(icon)
        self.connectDevice.setObjectName("connectDevice")
        self.horizontalLayout.addWidget(self.connectDevice)
        self.connectionStatus = QtWidgets.QLabel(footerWidget)
        self.connectionStatus.setObjectName("connectionStatus")
        self.horizontalLayout.addWidget(self.connectionStatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(footerWidget)
        QtCore.QMetaObject.connectSlotsByName(footerWidget)

    def retranslateUi(self, footerWidget):
        _translate = QtCore.QCoreApplication.translate
        footerWidget.setWindowTitle(_translate("footerWidget", "Form"))
        self.connectDevice.setToolTip(_translate("footerWidget", "<font color=black>Move down (CTRL+Down)</font>"))
        self.connectionStatus.setText(_translate("footerWidget", "No DFU device found"))
