# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\cdf_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cdfEdit(object):
    def setupUi(self, cdfEdit):
        cdfEdit.setObjectName("cdfEdit")
        cdfEdit.resize(417, 173)
        self.gridLayout = QtWidgets.QGridLayout(cdfEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.copyTable = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyTable.sizePolicy().hasHeightForWidth())
        self.copyTable.setSizePolicy(sizePolicy)
        self.copyTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.copyTable.setFont(font)
        self.copyTable.setObjectName("copyTable")
        self.gridLayout.addWidget(self.copyTable, 1, 0, 1, 1)
        self.pasteTable = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasteTable.sizePolicy().hasHeightForWidth())
        self.pasteTable.setSizePolicy(sizePolicy)
        self.pasteTable.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pasteTable.setFont(font)
        self.pasteTable.setObjectName("pasteTable")
        self.gridLayout.addWidget(self.pasteTable, 1, 1, 1, 1)
        self.Add = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add.sizePolicy().hasHeightForWidth())
        self.Add.setSizePolicy(sizePolicy)
        self.Add.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.gridLayout.addWidget(self.Add, 1, 2, 1, 1)
        self.Remove = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Remove.sizePolicy().hasHeightForWidth())
        self.Remove.setSizePolicy(sizePolicy)
        self.Remove.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Remove.setFont(font)
        self.Remove.setObjectName("Remove")
        self.gridLayout.addWidget(self.Remove, 1, 3, 1, 1)
        self.Clear = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear.sizePolicy().hasHeightForWidth())
        self.Clear.setSizePolicy(sizePolicy)
        self.Clear.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Clear.setFont(font)
        self.Clear.setObjectName("Clear")
        self.gridLayout.addWidget(self.Clear, 1, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(cdfEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 5)

        self.retranslateUi(cdfEdit)
        self.buttonBox.accepted.connect(cdfEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(cdfEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(cdfEdit)

    def retranslateUi(self, cdfEdit):
        _translate = QtCore.QCoreApplication.translate
        cdfEdit.setWindowTitle(_translate("cdfEdit", "DF Edit"))
        self.copyTable.setText(_translate("cdfEdit", "Copy Table"))
        self.pasteTable.setText(_translate("cdfEdit", "Paste Table"))
        self.Add.setText(_translate("cdfEdit", "Add"))
        self.Remove.setText(_translate("cdfEdit", "Remove"))
        self.Clear.setText(_translate("cdfEdit", "Clear"))
        self.lineEdit.setPlaceholderText(_translate("cdfEdit", "Comment here"))
import res_rc
