# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


defaultStyleSheet = """
                QWidget {
                            background-color: rgb(55, 52, 63);
                            border: 1px solid rgb(68, 68, 68);
                            color: white;
                            font-size: 15px;
                        }
                
                QWidget::hover {
                    background-color: orange;
                    color: black;
                }
                
                QLabel {
                    border: 0;
                    background-color: transparent;
                }
                
                QSpinBox::up-button { width: 20px; }
                QSpinBox::down-button { width: 20px; }
                QSpinBox, QDoubleSpinBox {
                    background-color: rgb(51, 51, 51);
                    color: rgb(255, 255, 255);
                    border: 0;
                }

                QSpinBox::hover, QDoubleSpinBox::hover {
                    color: rgb(255, 255, 255);
                    background-color: rgb(51, 51, 51);
                }
        """

selectedStyleSheet = """
                QWidget {
                    background-color: orange;
                    border: 1px solid orange;
                    color: black;
                    font-size: 15px;
                }
                                
                QWidget::hover {
                    background-color: orange;
                    color: black;
                }
                
                QLabel {
                    border: 0;
                    background-color: transparent;
                }
                
                QSpinBox::up-button { width: 20px; }
                QSpinBox::down-button { width: 20px; }
                QSpinBox, QDoubleSpinBox {
                    background-color: rgb(51, 51, 51);
                    color: rgb(255, 255, 255);
                    border: 0;
                }

                QSpinBox::hover, QDoubleSpinBox::hover {
                    color: rgb(255, 255, 255);
                    background-color: rgb(51, 51, 51);
                }
        """

class CST(object):
    def __init__(self):
        pass

class NoWheelDoubleSpinBox(QtWidgets.QDoubleSpinBox):
    def wheelEvent(self, event):
        event.ignore()


class NoWheelSpinBox(QtWidgets.QSpinBox):
    def wheelEvent(self, event):
        event.ignore()


class WProfileItem(QtWidgets.QWidget):
    def __init__(self,
                 index,
                 cst: CST = None,
                 parent=None):
        super().__init__(parent)
        self.index = index
        self.cst = cst if cst else CST()

        self.defStyle = defaultStyleSheet
        self.selStyle = selectedStyleSheet

        self.setGeometry(QtCore.QRect(10, 10, 410, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(0, 60))
        self.setMaximumSize(QtCore.QSize(410, 60))
        self.setStyleSheet(self.defStyle)
        self.setObjectName(f"WProfileItem{index}")
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")

        self.widget_2 = QtWidgets.QWidget(self)
        self.widget_2.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(50, 50))
        self.widget_2.setStyleSheet(  # Tw Cen MT Condensed / Bahnschrift Light Condensed
            """ 
                QWidget {
                    background-color: black;
                    color: black;
                    font-size: 16px;
                    font-family: "Bahnschrift Light Condensed"; 
                }
                QLabel {
                    background-color: white;
                }
            """)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.caliberShort = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caliberShort.sizePolicy().hasHeightForWidth())
        self.caliberShort.setSizePolicy(sizePolicy)
        self.caliberShort.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.caliberShort.setFont(font)
        self.caliberShort.setStyleSheet("")
        self.caliberShort.setAlignment(QtCore.Qt.AlignCenter)
        self.caliberShort.setObjectName("caliberShort")
        self.verticalLayout.addWidget(self.caliberShort)
        self.tileBulletWeight = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileBulletWeight.sizePolicy().hasHeightForWidth())
        self.tileBulletWeight.setSizePolicy(sizePolicy)
        self.tileBulletWeight.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tileBulletWeight.setFont(font)
        self.tileBulletWeight.setStyleSheet("")
        self.tileBulletWeight.setAlignment(QtCore.Qt.AlignCenter)
        self.tileBulletWeight.setObjectName("tileBulletWeight")
        self.verticalLayout.addWidget(self.tileBulletWeight)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 2, 1)

        self.doubleSpinBox_x = NoWheelDoubleSpinBox(self)
        self.doubleSpinBox_x.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_x.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_x.setWrapping(False)
        self.doubleSpinBox_x.setFrame(True)
        self.doubleSpinBox_x.setReadOnly(False)
        self.doubleSpinBox_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_x.setAccelerated(False)
        self.doubleSpinBox_x.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_x.setKeyboardTracking(False)
        self.doubleSpinBox_x.setMinimum(-200.0)
        self.doubleSpinBox_x.setMaximum(200.0)
        self.doubleSpinBox_x.setSingleStep(0.25)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.gridLayout.addWidget(self.doubleSpinBox_x, 0, 4, 1, 1)
        self.rifleName = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rifleName.sizePolicy().hasHeightForWidth())
        self.rifleName.setSizePolicy(sizePolicy)
        self.rifleName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rifleName.setFont(font)
        self.rifleName.setObjectName("rifleName")
        self.gridLayout.addWidget(self.rifleName, 0, 3, 1, 1)
        self.spinBox_zeroing_distance = NoWheelSpinBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_zeroing_distance.sizePolicy().hasHeightForWidth())
        self.spinBox_zeroing_distance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.spinBox_zeroing_distance.setFont(font)
        self.spinBox_zeroing_distance.setStyleSheet("")
        self.spinBox_zeroing_distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_zeroing_distance.setPrefix("")
        self.spinBox_zeroing_distance.setMaximum(10000)
        self.spinBox_zeroing_distance.setSingleStep(10)
        self.spinBox_zeroing_distance.setProperty("value", 100)
        self.spinBox_zeroing_distance.setObjectName("spinBox_zeroing_distance")
        self.gridLayout.addWidget(self.spinBox_zeroing_distance, 0, 5, 2, 1)
        self.cartridgeName = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartridgeName.sizePolicy().hasHeightForWidth())
        self.cartridgeName.setSizePolicy(sizePolicy)
        self.cartridgeName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cartridgeName.setFont(font)
        self.cartridgeName.setObjectName("cartridgeName")
        self.gridLayout.addWidget(self.cartridgeName, 1, 3, 1, 1)
        self.doubleSpinBox_y = NoWheelDoubleSpinBox(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_y.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_y.setSizePolicy(sizePolicy)
        self.doubleSpinBox_y.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_y.setMinimum(-200.0)
        self.doubleSpinBox_y.setMaximum(200.0)
        self.doubleSpinBox_y.setSingleStep(0.25)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.gridLayout.addWidget(self.doubleSpinBox_y, 1, 4, 1, 1)
        self.label_count = QtWidgets.QLabel(self)
        self.label_count.setMinimumSize(QtCore.QSize(26, 0))
        self.label_count.setMaximumSize(QtCore.QSize(28, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_count.setFont(font)
        self.label_count.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count.setObjectName("label_count")
        self.gridLayout.addWidget(self.label_count, 0, 0, 2, 1)

        self.doubleSpinBox_x.lineEdit().setEnabled(False)
        self.doubleSpinBox_x.lineEdit().setObjectName(self.doubleSpinBox_x.objectName() + '_x')
        self.doubleSpinBox_x.setContextMenuPolicy(0)

        self.doubleSpinBox_y.lineEdit().setEnabled(False)
        self.doubleSpinBox_y.lineEdit().setObjectName(self.doubleSpinBox_x.objectName() + '_y')
        self.doubleSpinBox_y.setContextMenuPolicy(0)

        # self.gridLayout.addWidget(self.doubleSpinBox_x, 0, 3, 1, 1)

        for le in self.findChildren(QtWidgets.QLineEdit):
            le.editingFinished.connect(self.window().update_current_profile)
        for cb in self.findChildren(QtWidgets.QComboBox):
            cb.currentIndexChanged.connect(self.window().update_current_profile)

    def fill_data(self, cartridge=''):
        # _translate = QtCore.QCoreApplication.translate
        self.doubleSpinBox_y.setPrefix("Y: ")
        self.spinBox_zeroing_distance.setSuffix(" m")
        self.doubleSpinBox_x.setPrefix("X: ")
        # self.caliberShort.setText("")
        # self.tileBulletWeight.setText("")

    def paintEvent(self, pe):
        o = QtWidgets.QStyleOption()
        o.initFrom(self)
        p = QtGui.QPainter(self)
        self.style().drawPrimitive(QtWidgets.QStyle.PE_Widget, o, p, self)

    def set_current(self):
        child = self.parent().findChild(WProfileItem, f'WProfileItem{self.window().state.current_profile}')
        if child:
            child.setStyleSheet(self.defStyle)
        self.window().state.current_profile = self.index
        self.setStyleSheet(self.selStyle)

    def mousePressEvent(self, event=None):
        self.set_current()
        self.window().fill_profile(self)
