# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 81)
        Form.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 415, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setMaximumSize(QtCore.QSize(415, 60))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QWidget {\n"
                                  "    background-color: rgb(55, 52, 63);\n"
                                  "    border: 1px solid rgb(78, 78, 78);\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    font-size: 15px;\n"
                                  "}\n"
                                  "\n"
                                  "QLabel {\n"
                                  "    border: 0;\n"
                                  "    background-color: transparent;\n"
                                  "}\n"
                                  "\n"
                                  "QWidget::hover {\n"
                                  "    background-color: orange;\n"
                                  "    color: black;\n"
                                  "}\n"
                                  "\n"
                                  "QSpinBox::up-button, QDoubleSpinBox::up-button { width: 20px; }\n"
                                  "QSpinBox::down-button, QDoubleSpinBox::down-button { width: 20px; }\n"
                                  "QSpinBox, QDoubleSpinBox {\n"
                                  "    background-color: rgb(40, 40, 40);\n"
                                  "    alternate-background-color: rgb(40, 40, 40);\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    border: 0;\n"
                                  "}\n"
                                  "QLineEdit, QLabel, QComboBox, QPushButton, QToolButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "}\n"
                                  "QLineEdit {\n"
                                  "    border: 0px solid grey;\n"
                                  "    background-color: rgb(40, 40, 40);\n"
                                  "}\n"
                                  "\n"
                                  "\n"
                                  "")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: black;\n"
                                    "font-size: 16px;\n"
                                    "font-family: \"Bahnschrift Light Condensed\";")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.caliberShort = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caliberShort.sizePolicy().hasHeightForWidth())
        self.caliberShort.setSizePolicy(sizePolicy)
        self.caliberShort.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.caliberShort.setFont(font)
        self.caliberShort.setStyleSheet("")
        self.caliberShort.setAlignment(QtCore.Qt.AlignCenter)
        self.caliberShort.setObjectName("caliberShort")
        self.verticalLayout.addWidget(self.caliberShort)
        self.bulletWeight = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bulletWeight.sizePolicy().hasHeightForWidth())
        self.bulletWeight.setSizePolicy(sizePolicy)
        self.bulletWeight.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        font.setPointSize(-1)
        self.bulletWeight.setFont(font)
        self.bulletWeight.setStyleSheet("")
        self.bulletWeight.setAlignment(QtCore.Qt.AlignCenter)
        self.bulletWeight.setObjectName("bulletWeight")
        self.verticalLayout.addWidget(self.bulletWeight)
        self.gridLayout.addWidget(self.widget_2, 0, 2, 2, 1)
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_x.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_x.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_x.setSizePolicy(sizePolicy)
        self.doubleSpinBox_x.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_x.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_x.setWrapping(False)
        self.doubleSpinBox_x.setFrame(True)
        self.doubleSpinBox_x.setReadOnly(False)
        self.doubleSpinBox_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_x.setAccelerated(False)
        self.doubleSpinBox_x.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_x.setKeyboardTracking(False)
        self.doubleSpinBox_x.setMinimum(-200.0)
        self.doubleSpinBox_x.setMaximum(200.0)
        self.doubleSpinBox_x.setSingleStep(0.25)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.gridLayout.addWidget(self.doubleSpinBox_x, 0, 4, 1, 1)
        self.rifleName = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rifleName.sizePolicy().hasHeightForWidth())
        self.rifleName.setSizePolicy(sizePolicy)
        self.rifleName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.rifleName.setFont(font)
        self.rifleName.setObjectName("rifleName")
        self.gridLayout.addWidget(self.rifleName, 0, 3, 1, 1)
        self.spinBox_zeroing_distance = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_zeroing_distance.sizePolicy().hasHeightForWidth())
        self.spinBox_zeroing_distance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.spinBox_zeroing_distance.setFont(font)
        self.spinBox_zeroing_distance.setStyleSheet("")
        self.spinBox_zeroing_distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_zeroing_distance.setPrefix("")
        self.spinBox_zeroing_distance.setMaximum(10000)
        self.spinBox_zeroing_distance.setSingleStep(10)
        self.spinBox_zeroing_distance.setProperty("value", 100)
        self.spinBox_zeroing_distance.setObjectName("spinBox_zeroing_distance")
        self.gridLayout.addWidget(self.spinBox_zeroing_distance, 0, 5, 2, 1)
        self.cartridgeName = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartridgeName.sizePolicy().hasHeightForWidth())
        self.cartridgeName.setSizePolicy(sizePolicy)
        self.cartridgeName.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.cartridgeName.setFont(font)
        self.cartridgeName.setObjectName("cartridgeName")
        self.gridLayout.addWidget(self.cartridgeName, 1, 3, 1, 1)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_y.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_y.setSizePolicy(sizePolicy)
        self.doubleSpinBox_y.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBox_y.setMinimum(-200.0)
        self.doubleSpinBox_y.setMaximum(200.0)
        self.doubleSpinBox_y.setSingleStep(0.25)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.gridLayout.addWidget(self.doubleSpinBox_y, 1, 4, 1, 1)
        self.label_count = QtWidgets.QLabel(self.widget)
        self.label_count.setMinimumSize(QtCore.QSize(26, 0))
        self.label_count.setMaximumSize(QtCore.QSize(28, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_count.setFont(font)
        self.label_count.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count.setObjectName("label_count")
        self.gridLayout.addWidget(self.label_count, 0, 0, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.caliberShort.setText(_translate("Form", ".223Rem"))
        self.bulletWeight.setText(_translate("Form", "69"))
        self.doubleSpinBox_x.setPrefix(_translate("Form", "X: "))
        self.rifleName.setText(_translate("Form", "223Rem 8TWIST   p"))
        self.spinBox_zeroing_distance.setSuffix(_translate("Form", " m"))
        self.cartridgeName.setText(_translate("Form", "ABR 69GR SMK"))
        self.doubleSpinBox_y.setPrefix(_translate("Form", "Y: "))
        self.label_count.setText(_translate("Form", "1"))
