# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\drop_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_BCTable(QtWidgets.QTableWidget):
    def setupUi(self):
        self.setMinimumSize(QtCore.QSize(140, 0))
        self.setMaximumSize(QtCore.QSize(140, 16777215))
        self.setObjectName("bcTable")
        self.setColumnCount(2)
        self.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.setHorizontalHeaderItem(1, item)
        self.verticalHeader().setVisible(False)
        self.verticalHeader().setDefaultSectionSize(26)
        self.verticalHeader().setMinimumSectionSize(26)
        self.verticalHeader().setMinimumHeight(26)
        self.verticalHeader().setMaximumHeight(26)
        self.setMaximumHeight(156)
        self.setMinimumHeight(156)
        self.horizontalHeader().setDefaultSectionSize(70)
        self.horizontalHeader().setMinimumSectionSize(45)
        self.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.retranslateUi(self)
        # QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        item = self.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Speed"))
        item = self.horizontalHeaderItem(1)
        item.setText(_translate("Form", "BC"))
