# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\drag_func_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DragFuncEditDialog(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(736, 493)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(736, 493))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_templates\\../.rsrc/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(51, 51, 51);\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(51, 51, 51);\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button { width: 20px; }\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button { width: 20px; }\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: rgb(40, 40, 40);\n"
"    alternate-background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit, QLabel, QComboBox, QPushButton, QToolButton {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    border: 0px solid grey;\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"QGroupBox {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(78, 78, 78);\n"
"    padding-top: 25px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    padding: 5px 20px 5px 20px;\n"
"    color: rgb(255, 170, 0);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Down = QtWidgets.QPushButton(self.widget_3)
        self.Down.setMinimumSize(QtCore.QSize(0, 0))
        self.Down.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Down.setObjectName("Down")
        self.horizontalLayout_3.addWidget(self.Down)
        self.PeakDown = QtWidgets.QPushButton(self.widget_3)
        self.PeakDown.setMinimumSize(QtCore.QSize(0, 0))
        self.PeakDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PeakDown.setObjectName("PeakDown")
        self.horizontalLayout_3.addWidget(self.PeakDown)
        self.EndDown = QtWidgets.QPushButton(self.widget_3)
        self.EndDown.setMinimumSize(QtCore.QSize(0, 0))
        self.EndDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EndDown.setObjectName("EndDown")
        self.horizontalLayout_3.addWidget(self.EndDown)
        self.gridLayout.addWidget(self.widget_3, 3, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Up = QtWidgets.QPushButton(self.widget_2)
        self.Up.setMinimumSize(QtCore.QSize(0, 0))
        self.Up.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Up.setObjectName("Up")
        self.horizontalLayout_2.addWidget(self.Up)
        self.PeakUp = QtWidgets.QPushButton(self.widget_2)
        self.PeakUp.setMinimumSize(QtCore.QSize(0, 0))
        self.PeakUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PeakUp.setObjectName("PeakUp")
        self.horizontalLayout_2.addWidget(self.PeakUp)
        self.EndUp = QtWidgets.QPushButton(self.widget_2)
        self.EndUp.setMinimumSize(QtCore.QSize(0, 0))
        self.EndUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.EndUp.setObjectName("EndUp")
        self.horizontalLayout_2.addWidget(self.EndUp)
        self.gridLayout.addWidget(self.widget_2, 2, 1, 1, 1)
        self.Step = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Step.sizePolicy().hasHeightForWidth())
        self.Step.setSizePolicy(sizePolicy)
        self.Step.setMinimumSize(QtCore.QSize(69, 0))
        self.Step.setMaximum(100)
        self.Step.setObjectName("Step")
        self.gridLayout.addWidget(self.Step, 3, 0, 1, 1)
        self.labelStep = QtWidgets.QLabel(Form)
        self.labelStep.setMinimumSize(QtCore.QSize(69, 0))
        self.labelStep.setObjectName("labelStep")
        self.gridLayout.addWidget(self.labelStep, 2, 0, 1, 1)
        self.bcTable = QtWidgets.QTableWidget(Form)
        self.bcTable.setMinimumSize(QtCore.QSize(140, 0))
        self.bcTable.setMaximumSize(QtCore.QSize(140, 16777215))
        self.bcTable.setObjectName("bcTable")
        self.bcTable.setColumnCount(2)
        self.bcTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.bcTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bcTable.setHorizontalHeaderItem(1, item)
        self.bcTable.horizontalHeader().setDefaultSectionSize(60)
        self.bcTable.horizontalHeader().setMinimumSectionSize(45)
        self.gridLayout.addWidget(self.bcTable, 0, 0, 2, 1)
        self.dragTable = QtWidgets.QTableWidget(Form)
        self.dragTable.setEnabled(True)
        self.dragTable.setMaximumSize(QtCore.QSize(16777215, 80))
        self.dragTable.setWordWrap(True)
        self.dragTable.setObjectName("dragTable")
        self.dragTable.setColumnCount(0)
        self.dragTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.dragTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dragTable.setVerticalHeaderItem(1, item)
        self.dragTable.horizontalHeader().setVisible(False)
        self.dragTable.horizontalHeader().setDefaultSectionSize(60)
        self.dragTable.horizontalHeader().setMinimumSectionSize(28)
        self.dragTable.verticalHeader().setDefaultSectionSize(28)
        self.dragTable.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout.addWidget(self.dragTable, 4, 0, 1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 4)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioDrag = QtWidgets.QRadioButton(self.widget)
        self.radioDrag.setChecked(False)
        self.radioDrag.setObjectName("radioDrag")
        self.horizontalLayout.addWidget(self.radioDrag)
        self.radioDrop = QtWidgets.QRadioButton(self.widget)
        self.radioDrop.setChecked(True)
        self.radioDrop.setObjectName("radioDrop")
        self.horizontalLayout.addWidget(self.radioDrop)
        self.gridLayout.addWidget(self.widget, 2, 2, 1, 1)
        self.distanceQuantity = QtWidgets.QComboBox(Form)
        self.distanceQuantity.setObjectName("distanceQuantity")
        self.distanceQuantity.addItem("")
        self.distanceQuantity.addItem("")
        self.distanceQuantity.addItem("")
        self.gridLayout.addWidget(self.distanceQuantity, 3, 2, 1, 1)
        self.holdOffQuantity = QtWidgets.QComboBox(Form)
        self.holdOffQuantity.setObjectName("holdOffQuantity")
        self.holdOffQuantity.addItem("")
        self.holdOffQuantity.addItem("")
        self.holdOffQuantity.addItem("")
        self.gridLayout.addWidget(self.holdOffQuantity, 3, 3, 1, 1)
        self.Calculate = QtWidgets.QPushButton(Form)
        self.Calculate.setObjectName("Calculate")
        self.gridLayout.addWidget(self.Calculate, 2, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Down.setText(_translate("Form", "Down"))
        self.PeakDown.setText(_translate("Form", "Peak Down"))
        self.EndDown.setText(_translate("Form", "End Down"))
        self.Up.setText(_translate("Form", "Up"))
        self.PeakUp.setText(_translate("Form", "Peak Up"))
        self.EndUp.setText(_translate("Form", "End Up"))
        self.Step.setSuffix(_translate("Form", " %"))
        self.labelStep.setText(_translate("Form", "Step"))
        item = self.bcTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Speed"))
        item = self.bcTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "BC"))
        item = self.dragTable.verticalHeaderItem(0)
        item.setText(_translate("Form", "x"))
        item = self.dragTable.verticalHeaderItem(1)
        item.setText(_translate("Form", "y"))
        self.radioDrag.setText(_translate("Form", "Drag"))
        self.radioDrop.setText(_translate("Form", "Drop"))
        self.distanceQuantity.setItemText(0, _translate("Form", "Mach"))
        self.distanceQuantity.setItemText(1, _translate("Form", "m/s"))
        self.distanceQuantity.setItemText(2, _translate("Form", "ft/s"))
        self.holdOffQuantity.setItemText(0, _translate("Form", "sm"))
        self.holdOffQuantity.setItemText(1, _translate("Form", "MIL"))
        self.holdOffQuantity.setItemText(2, _translate("Form", "MOA"))
        self.Calculate.setText(_translate("Form", "Calculate"))
