# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\drop_table_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dropTableEdit(object):
    def setupUi(self, dropTableEdit):
        dropTableEdit.setObjectName("dropTableEdit")
        dropTableEdit.resize(200, 318)
        dropTableEdit.setMinimumSize(QtCore.QSize(200, 0))
        dropTableEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(dropTableEdit)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addRow = QtWidgets.QPushButton(dropTableEdit)
        self.addRow.setObjectName("addRow")
        self.gridLayout.addWidget(self.addRow, 1, 0, 1, 1)
        self.removeRow = QtWidgets.QPushButton(dropTableEdit)
        self.removeRow.setObjectName("removeRow")
        self.gridLayout.addWidget(self.removeRow, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(dropTableEdit)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(dropTableEdit)
        QtCore.QMetaObject.connectSlotsByName(dropTableEdit)

    def retranslateUi(self, dropTableEdit):
        _translate = QtCore.QCoreApplication.translate
        dropTableEdit.setWindowTitle(_translate("dropTableEdit", "Form"))
        self.addRow.setText(_translate("dropTableEdit", "Add Row"))
        self.removeRow.setText(_translate("dropTableEdit", "Remove Row"))
