# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\drop_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dropTable(object):
    def setupUi(self, dropTable):
        dropTable.setObjectName("dropTable")
        dropTable.resize(200, 296)
        self.gridLayout = QtWidgets.QGridLayout(dropTable)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(dropTable)
        self.tableWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(dropTable)
        QtCore.QMetaObject.connectSlotsByName(dropTable)

    def retranslateUi(self, dropTable):
        _translate = QtCore.QCoreApplication.translate
        dropTable.setWindowTitle(_translate("dropTable", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dropTable", "Dist."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dropTable", "Drop."))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dropTable", "Correction"))
