# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\cdf_edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cdfEdit(object):
    def setupUi(self, cdfEdit):
        cdfEdit.setObjectName("cdfEdit")
        cdfEdit.resize(417, 173)
        self.gridLayout = QtWidgets.QGridLayout(cdfEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.copyTable = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyTable.sizePolicy().hasHeightForWidth())
        self.copyTable.setSizePolicy(sizePolicy)
        self.copyTable.setMinimumSize(QtCore.QSize(0, 0))
        self.copyTable.setObjectName("copyTable")
        self.gridLayout.addWidget(self.copyTable, 1, 0, 1, 1)
        self.pasteTable = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasteTable.sizePolicy().hasHeightForWidth())
        self.pasteTable.setSizePolicy(sizePolicy)
        self.pasteTable.setMinimumSize(QtCore.QSize(0, 0))
        self.pasteTable.setObjectName("pasteTable")
        self.gridLayout.addWidget(self.pasteTable, 1, 1, 1, 1)
        self.copyTable_2 = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyTable_2.sizePolicy().hasHeightForWidth())
        self.copyTable_2.setSizePolicy(sizePolicy)
        self.copyTable_2.setMinimumSize(QtCore.QSize(0, 0))
        self.copyTable_2.setObjectName("copyTable_2")
        self.gridLayout.addWidget(self.copyTable_2, 1, 2, 1, 1)
        self.copyTable_3 = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyTable_3.sizePolicy().hasHeightForWidth())
        self.copyTable_3.setSizePolicy(sizePolicy)
        self.copyTable_3.setMinimumSize(QtCore.QSize(0, 0))
        self.copyTable_3.setObjectName("copyTable_3")
        self.gridLayout.addWidget(self.copyTable_3, 1, 3, 1, 1)
        self.copyTable_4 = QtWidgets.QPushButton(cdfEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyTable_4.sizePolicy().hasHeightForWidth())
        self.copyTable_4.setSizePolicy(sizePolicy)
        self.copyTable_4.setMinimumSize(QtCore.QSize(0, 0))
        self.copyTable_4.setObjectName("copyTable_4")
        self.gridLayout.addWidget(self.copyTable_4, 1, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(cdfEdit)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(cdfEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 5)

        self.retranslateUi(cdfEdit)
        self.buttonBox.accepted.connect(cdfEdit.accept) # type: ignore
        self.buttonBox.rejected.connect(cdfEdit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(cdfEdit)

    def retranslateUi(self, cdfEdit):
        _translate = QtCore.QCoreApplication.translate
        cdfEdit.setWindowTitle(_translate("cdfEdit", "DF Edit"))
        self.copyTable.setText(_translate("cdfEdit", "Copy Table"))
        self.pasteTable.setText(_translate("cdfEdit", "Paste Table"))
        self.copyTable_2.setText(_translate("cdfEdit", "Add"))
        self.copyTable_3.setText(_translate("cdfEdit", "Remove"))
        self.copyTable_4.setText(_translate("cdfEdit", "Clear"))
        self.lineEdit.setPlaceholderText(_translate("cdfEdit", "Comment here"))
