# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_templates\db_filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter(object):
    def setupUi(self, filter):
        filter.setObjectName("filter")
        filter.resize(329, 204)
        filter.setMinimumSize(QtCore.QSize(0, 204))
        self.gridLayout = QtWidgets.QGridLayout(filter)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(filter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.weight = QtWidgets.QDoubleSpinBox(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weight.sizePolicy().hasHeightForWidth())
        self.weight.setSizePolicy(sizePolicy)
        self.weight.setObjectName("weight")
        self.gridLayout.addWidget(self.weight, 4, 1, 1, 1)
        self.diameter = QtWidgets.QDoubleSpinBox(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameter.sizePolicy().hasHeightForWidth())
        self.diameter.setSizePolicy(sizePolicy)
        self.diameter.setObjectName("diameter")
        self.gridLayout.addWidget(self.diameter, 3, 1, 1, 1)
        self.applyFilter = QtWidgets.QPushButton(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyFilter.sizePolicy().hasHeightForWidth())
        self.applyFilter.setSizePolicy(sizePolicy)
        self.applyFilter.setObjectName("applyFilter")
        self.gridLayout.addWidget(self.applyFilter, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(filter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(filter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(filter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(filter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.resetFilter = QtWidgets.QPushButton(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetFilter.sizePolicy().hasHeightForWidth())
        self.resetFilter.setSizePolicy(sizePolicy)
        self.resetFilter.setObjectName("resetFilter")
        self.gridLayout.addWidget(self.resetFilter, 0, 2, 1, 1)
        self.name = QtWidgets.QLineEdit(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 2)
        self.caliber = QtWidgets.QComboBox(filter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caliber.sizePolicy().hasHeightForWidth())
        self.caliber.setSizePolicy(sizePolicy)
        self.caliber.setObjectName("caliber")
        self.gridLayout.addWidget(self.caliber, 2, 1, 1, 2)

        self.retranslateUi(filter)
        QtCore.QMetaObject.connectSlotsByName(filter)

    def retranslateUi(self, filter):
        _translate = QtCore.QCoreApplication.translate
        filter.setWindowTitle(_translate("filter", "Filter"))
        self.label_4.setText(_translate("filter", "Name:"))
        self.applyFilter.setText(_translate("filter", "Filter"))
        self.label_5.setText(_translate("filter", "Filter:"))
        self.label_3.setText(_translate("filter", "Bullet weight:"))
        self.label.setText(_translate("filter", "Caliber:"))
        self.label_2.setText(_translate("filter", "Diameter:"))
        self.resetFilter.setText(_translate("filter", "Reset"))
